site: Peaceable Writer
title: Peaceable Writer
author: JD Eames
description: JD's thoughts

url: https://www.jdeames.com
baseurl: ""

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  haiku:
    output: true
    permalilnk: /haiku/:slug
  pens:
    output: true
    permalink: /pens/:slug
  notebooks:
    output: true
    permalink: /notebooks/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "haiku"
    values:
      layout: "haiku"
  -     
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "notebooks"
    values:
      layout: "notebook"
  -
    scope:
      path: ""
      type: "bio"
    values:
      layout: "page"     
  - 
    scope:
      path: ""
      type: "pens"
    values:
      layout: "pen"
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


markdown: kramdown
require: kramdown-parser-gfm

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

paginate: 2
paginate_path: "/blog/page:num/"

jekyll-archives:
  enabled: all
  layout: archive
 

feed:
  collections:
    haiku:
      path: "/pwhaiku.xml"
    notebooks:
      path: "/pwnotebooks.xml"
    pens:
      path: "/pwpens.xml"